<a href="https://colab.research.google.com/github/Akashkumar12/AI-ML/blob/main/AIML27_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import Required Libraries
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error

In [ ]:
X = np.array([[1],[2],[3]])
y = np.array([2,4,5])

In [ ]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [ ]:
model.predict(np.array([[4]]))

array([6.66666667])

In [ ]:
print(model.coef_)
print(model.intercept_)

[1.5]
0.666666666666667

In [ ]:
y_predict=model.predict(X)   #y = 0.66 + (1.5) x
y_predict

In [ ]:
mse = mean_squared_error(y,y_predict)
mse

0.05555555555555556

In [ ]:
model.score(X,y)

0.9642857142857143

In [ ]:
#import all required libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("/content/auto-mpg.data",names=["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year","origin","car_name"],sep="\s+",na_values='?')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3659/4227784541.py:1: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv("/content/auto-mpg.data",names=["mpg","cylinders","displacement","horsepower","weight","acceleration","model_year","origin","car_name"],sep="\s+",na_values='?')

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [ ]:
X = df[['cylinders', 'displacement', 'horsepower', 'weight','acceleration']]
y = df['mpg']

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [ ]:
lr  = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_predict = lr.predict(X_test)

In [ ]:
lr.score(X_test,y_test)  #NO

0.6485312110889081

In [ ]:
lr.coef_

array([-0.29950769, -0.70154521, -1.88013307, -4.23468085, -0.16655766])

In [ ]:
lr.intercept_

np.float64(23.657532829380898)

In [ ]:
lr.score(X_train,y_train)

0.7166422136497115

In [ ]:
import joblib
joblib.dump(lr,"mymodel")
joblib.dump(scaler,"scalermodel")

['scalermodel']

In [34]:
import gradio as gr
import joblib
def predict_mpg(cylinders,displacement,horsepower,weight,acceleration):
  input_data = [[cylinders,displacement,horsepower,weight,acceleration]]
  model = joblib.load("/content/mymodel")
  scaler = joblib.load("/content/scalermodel")
  input_scaled = scaler.transform(input_data)
  prediction = model.predict(input_scaled)
  return round(prediction[0],2)
app = gr.Interface(
    fn=predict_mpg,inputs=["number","number","number","number","number"],outputs="number",title="Auto MPG Prediction"
)
app.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ac6ab08e6c15863abc.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)