<a href="https://colab.research.google.com/github/Akashkumar12/AI-ML/blob/main/Copy_of_LinearClassifierAIML27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import SGDClassifier

In [2]:
X = np.array([
    [2,1],
    [1,2],
    [-1,-1],
    [-2,-1],
    [1,-1]
])
y = np.array([1,1,-1,-1,1])

In [3]:
clf = SGDClassifier(
    learning_rate='constant',
    eta0=0.1,
    alpha=0.0,
    max_iter=1,
    shuffle=False,
    fit_intercept=True,
    tol=None,
    random_state=42
)

In [4]:
clf.fit(X,y)

SGDClassifier(alpha=0.0, eta0=0.1, learning_rate='constant', max_iter=1,
              random_state=42, shuffle=False, tol=None)

In [5]:
w1,w2 = clf.coef_[0]
print(f" w1 = {w1:.4f}")
print(f" w2 = {w2:.4f}")

 w1 = 0.5000
 w2 = 0.3000

In [6]:
b = clf.intercept_[0]
print(f"intercept: {b}")

intercept: 0.2

In [7]:
clf.score(X,y)

1.0

In [8]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv("iris.csv")

In [10]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [12]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [15]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [18]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42)

In [20]:
model = SGDClassifier()

In [21]:
model.fit(X_train,y_train)

SGDClassifier()

In [22]:
model.score(X_test,y_test)

1.0

In [23]:
model.predict([[5.1	,3.5,	1.4	,0.2	]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(

array(['setosa'], dtype='<U10')