<a href="https://colab.research.google.com/github/Akashkumar12/AI-ML/blob/main/LinearClassifierAIML27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import SGDClassifier

In [ ]:
X = np.array([
    [2,1],
    [1,2],
    [-1,-1],
    [-2,-1],
    [1,-1]
])
y = np.array([1,1,-1,-1,1])

In [ ]:
clf = SGDClassifier(
    learning_rate='constant',
    eta0=0.1,
    alpha=0.0,
    max_iter=1,
    shuffle=False,
    fit_intercept=True,
    tol=None,
    random_state=42
)

In [ ]:
clf.fit(X,y)

SGDClassifier(alpha=0.0, eta0=0.1, learning_rate='constant', max_iter=1,
              random_state=42, shuffle=False, tol=None)

In [ ]:
w1,w2 = clf.coef_[0]
print(f" w1 = {w1:.4f}")
print(f" w2 = {w2:.4f}")

 w1 = 0.5000
 w2 = 0.3000

In [ ]:
b = clf.intercept_[0]
print(f"intercept: {b}")

intercept: 0.2

In [ ]:
clf.score(X,y)

1.0

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("iris.csv")

In [ ]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [ ]:
df.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [ ]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
y = df['variety']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42)

In [ ]:
model = SGDClassifier()   #optuna gridsearchcv

In [ ]:
model.fit(X_train,y_train)

SGDClassifier()

In [ ]:
model.score(X_test,y_test)

0.9333333333333333

In [ ]:
model.predict([[5.1	,3.5,	1.4	,0.2	]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(

array(['Setosa'], dtype='<U10')

In [ ]:
model.coef_[0]

array([  5.61510975,  23.48136804, -32.66972945, -15.8244002 ])

In [ ]:
import joblib

In [ ]:
from math import exp
(1/(1+exp(-25)))   #class 1

0.999999999986112

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("iris.csv")

In [ ]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [ ]:
df.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [ ]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [ ]:
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
y = df['variety']

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
lg = LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
lg.score(X_test,y_test)

1.0

In [ ]:
lg.predict([[5.8,3.1]])

In [ ]:
X = np.array([[20],[21],[24]])
y = np.array([24,25,26])

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

In [ ]:
lr.predict([[20],[21],[24]])

array([24.23076923, 24.69230769, 26.07692308])

In [ ]:
predicted = [24.23,24.69,26.07]

In [ ]:
for i in predicted:
  result = 1/(1+exp(-i))  #sigmoid
  if result >= 0.5:
    print("max")
  else:
    print("min")

max
max
max

In [ ]:
#logistic regression
X = np.array([[20],[21],[24]])
y = np.array([0,1,1])

In [ ]:
lg = LogisticRegression()
lg.fit(X,y)

LogisticRegression()

In [ ]:
lg.predict([[20],[21],[24]])

array([0, 1, 1])